### ISSUE TITLE
Healthcheck issue when another app listens on port 8000

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/onlyoffice_ynh#103]
### Describe the bug

Any request to `/healthcheck` is resulting in a 404 error.

### Context

I already have a docker app running on port 8000 (I know, docker is not recommended but there is no yunohost package for this app yet).

Once I stopped this app, I was able to run OnlyOffice and the healtcheck worked.

### Steps to reproduce

   1. Have an app running on port 8000
   2. Try to configure nextcloud with OnlyOffice

### Expected behavior

Everything works fine after setting the right onlyoffice domain and secret key.

### Logs

In `/var/log/onlyoffice/documentserver/docservice/out.log` here are the errors:

```
[2023-07-05T09:42:46.963] [ERROR] [localhost] [docId] [userId] nodeJS - Error: listen EADDRINUSE: address already in use :::8000
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at /snapshot/server/build/server/DocService/sources/server.js
    at /snapshot/server/build/server/DocService/sources/DocsCoServer.js
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by nicofrand** [comment]
`netstat` returns both nginx and dockservice:

```
tcp6       0      0 :::8000                 :::*                    LISTEN      2956033/docservice  
tcp6       0      0 :::8096                 :::*                    LISTEN      2948701/nginx: mast 
```

while nginx proxies to 8096 as expected: `proxy_pass        http://127.0.0.1:8096/;`

**Comment by CodeShakingSheep** [comment]
I'm running into the same issue. In my case it's even a port conflict with another YNH app (appflowy) that also uses port 8000.

These are the logs from `/var/log/onlyoffice/documentserver/docservice/out.log`

```
[2025-04-16T18:28:40.297] [ERROR] [localhost] [docId] [userId] nodeJS - uncaughtException:Error: listen EADDRINUSE: address already in use :::8000
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at /snapshot/server/DocService/sources/server.js
    at /snapshot/server/DocService/sources/DocsCoServer.js
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

```
netstat -plnt | grep ':8000'
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      1605944/appflowy_cl
```

**Comment by cocochristmas** [comment]
https://afterlogic.com/docs/aurora/frequently-asked-questions/configuring-onlyoffice-docs-with-non-standard-port

**Comment by zamentur** [comment]
Fixed in https://github.com/YunoHost-Apps/onlyoffice_ynh/pull/164
