### ISSUE TITLE
Onlyoffice fails after upgrade, config file kept back [Solved]

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/onlyoffice_ynh#108]
### Describe the bug

Doc-service fails after a successful upgrade. The supervisord service keeps running, but doc edition is disabled. Only webpages are visible on the onlyoffice domain, not the editor.
In Nextcloud, the app settings gives a 503 error for the document-service url.

### Context

- Hardware: *VPS bought online on a proxmox setup*
- YunoHost version: 11.2.4
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: * yes*
  - If yes, please explain: nextcloud instance is on another VM on the ame Proxmox Setup.
- Using, or trying to install package version/branch: 7.3.3~ynh1
- If upgrading, current package version: *TBD*

### Steps to reproduce

Upgrade the app via CLI, then try to edit a doc drom Nextcloud.

### Expected behavior
App should work the same as before.

### Logs
* upgrade : https://paste.yunohost.org/raw/enolizibag

* Error from DS-docservice ( in `/var/log/onlyoffice/documentserver/docservice/err.log`) :
```
Error: Configuration property "bottleneck.getChanges" is not defined
    at Config.get (/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/snapshot/server/build/server/DocService/sources/baseConnector.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/snapshot/server/build/server/DocService/sources/DocsCoServer.js)
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

```

## :heavy_check_mark:  Solution

As pointed in [this issue](https://github.com/ONLYOFFICE/DocumentServer/issues/2082), it turns out that yunohost does not apply the last config file, because the default one has been modified (I don' remember doing it, maybe it's ynh fault ?).

So I went in the CLI, and replaced the default.json with the default.json.dpkg-dist  that had been kept back
A simple `service ds-docservice restart `made it work afterwards.
So I guess a warning message would be needed when upgrading. (or if it's there I missed it, so make it more visible, stopping the process maybe)

I'll leave you to fix this, dear maintainers :wink:

**Comment by Jaxom99** [comment]
ping @nahoj in case you want to add precisions...

**Comment by czen** [comment]
encountered this issue during upgrade between the 2 most recent ynh package versions on 25.10.23.

default.json had missing config options for `tenants.filenameConfig`, `services.CoAuthoring.server.allowPrivateIPAddresForSignedRequests`, and some others.

**Comment by Jaxom99** [comment]
I had the same problem from 7.3 to 7.5, only this time the new config file was nowhere to be found :open_mouth: 

I had to fetch it [from upstream](https://github.com/ONLYOFFICE/server/blob/f217a744e7e0e6e73cfb43d98af861e4e6c345df/Common/config/default.json) and paste it in `/etc/onlyoffice/documentserver` to make it work.

@ericgaspar Are you sure of your testing ? I'm still **very** grateful for the work you put in (i'm no packager myself...), but if you need help or 2nd looks when testing, feel free to ping me.

**Comment by nicofrand** [comment]
Same issue with the latest update (8.1.1~ynh1), using the .dpkg-dist worked fine, thanks for the tips!
