### ISSUE TITLE
OO won't start after upgrade from 7.5 to 8.0 - 502 error with missing parameters

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/onlyoffice_ynh#126]
### Describe the bug
Onlyoffice returns 502 errors after upgrading.

### Context

- Hardware: VPS on proxmox
- YunoHost version: 11.2.11.3
- I have access to my server: Through SSH and web
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 8.0.1~ynh1
- If upgrading, current package version: *7.5 something...*

### Steps to reproduce
1° upgrade tthrough CLI
2° errors 502 on web interface
3° the docserver logs shows an error because a setting is missing :  wopi.dummy.sampleFilePath 
4° I add the settings manually in `/etc/onlyoffice/documentserver.default.json` to a random location */tmp/wopi*
5° after service restart, same error with setting wopi.dummy.enable 
6° After adding this setting as 'false', the restart works alright.

### Expected behavior
Upgrade from yunohost should take care about missing settings.

### Logs
upgrade successful : https://paste.yunohost.org/raw/ewazumavub
Example of error messages : 
```
/snapshot/server/DocService/node_modules/config/lib/config.js:203
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "wopi.dummy.enable" is not defined
    at Config.get (/snapshot/server/DocService/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/snapshot/server/DocService/sources/server.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by Quiwy** [comment]
Same problem here.
Just added 
```
    "dummy": {
        "enable": true,
        "sampleFilePath": ""
    }
```
as described in the [onlyoffice doc](https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx), and working after service restart.

**Comment by ndx1905-github** [comment]
I have the same problem.
502 error, and added the 
```
 "dummy": {
        "enable": true,
        "sampleFilePath": ""
    }
```
in the wopi section as described.
Still have a 502 error after restart.
Are others encountering the same problem?

I am using an ARM64 VPS

**Comment by zamentur** [comment]
Fixed since we use the last default config
