### ISSUE TITLE
Config file is not upgraded with new app version

### ISSUE THREAD

**Issue by nathanael-h** [YunoHost-Apps/onlyoffice_ynh#137]
### Describe the bug

An upgrade of the app does not upgrade the config file `/etc/onlyoffice/documentserver/default.json`.

This make the app to enter a loop crash, because a key is missing in the config file. 
The error is `Configuration property "externalRequest.directIfIn" is not defined` 

I think the error is due to the way we update app that are installed using a deb file, we add the dpkg options `--force-confold`  in https://github.com/YunoHost/yunohost/blob/ea926845391c6c29a872aaeb1da4be1c7d4dcd87/helpers/helpers.v1.d/apt#L124C34-L124C49 

I don't know what would be the best solution to allow the upgrade of the config file "template" provided by the deb file, and also keep or set again the needed config values like database name user and password. 

### Logs

More logs :
```
Sep 23 11:29:40 domain.fr systemd[1]: ds-converter.service: Scheduled restart job, restart counter is at 93132.
Sep 23 11:29:40 domain.fr systemd[1]: Stopped ds-converter.service - Docs Converter.
Sep 23 11:29:40 domain.fr systemd[1]: Started ds-converter.service - Docs Converter.
Sep 23 11:29:40 domain.fr sh[420598]: pkg/prelude/bootstrap.js:1876
Sep 23 11:29:40 domain.fr sh[420598]:       throw error;
Sep 23 11:29:40 domain.fr sh[420598]:       ^
Sep 23 11:29:40 domain.fr sh[420598]: Error: Configuration property "externalRequest.directIfIn" is not defined
Sep 23 11:29:40 domain.fr sh[420598]:     at Config.get (/snapshot/server/Common/node_modules/config/lib/config.js:203:11)
Sep 23 11:29:40 domain.fr sh[420598]:     at Object.<anonymous> (/snapshot/server/Common/sources/utils.js)
Sep 23 11:29:40 domain.fr sh[420598]:     at Module._compile (pkg/prelude/bootstrap.js:1930:22)
Sep 23 11:29:40 domain.fr sh[420598]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
Sep 23 11:29:40 domain.fr sh[420598]:     at Module.load (node:internal/modules/cjs/loader:981:32)
Sep 23 11:29:40 domain.fr sh[420598]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Sep 23 11:29:40 domain.fr sh[420598]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
Sep 23 11:29:40 domain.fr sh[420598]:     at Module.require (pkg/prelude/bootstrap.js:1855:31)
Sep 23 11:29:40 domain.fr sh[420598]:     at require (node:internal/modules/cjs/helpers:102:18)
Sep 23 11:29:40 domain.fr sh[420598]:     at Object.<anonymous> (/snapshot/server/Common/sources/operationContext.js)
Sep 23 11:29:40 domain.fr systemd[1]: ds-converter.service: Deactivated successfully.

```

**Comment by zamentur** [comment]
Fixed in https://github.com/YunoHost-Apps/onlyoffice_ynh/pull/164
